[package]
name = "git-remote"
version = "0.1.0"
edition = "2021"
authors = ["Goudham Suresh <sgoudham@gmail.com>"]
description = ""
license = "MIT"
readme = "README.md"
repository = "https://github.com/sgoudham/git-remote"
exclude = [".github/**"]

[[bin]]
name = "git-remote"
path = "src/bin/git-remote.rs"

[lib]
name = "git_remote"
path = "src/lib.rs"

[dependencies]
clap = { version = '3.1.18' }
