name: build

on:
  push:
    paths-ignore:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
