name: build

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [ stable, beta ]
        target:
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./target
          # Example key: windows-stable-x86_64-pc-windows-gnu-3k4j234lksjfd9
          key: windows-${{ matrix.channel }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            windows-${{ matrix.channel }}-${{ matrix.target }}-
            windows-${{ matrix.channel }}-
            windows-
      - name: Set Rust Channel
        run: rustup default ${{ matrix.channel }}
        shell: bash
      - name: Set Rust Target
        run: rustup target add ${{ matrix.target }}
        shell: bash
      - name: Build
        run: cargo build --target ${{ matrix.target }}
        shell: bash
      - name: Test 
        run: cargo test --target ${{ matrix.target }}
        shell: bash

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [ stable, beta ]
        target:
          - x86_64-apple-darwin
          
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./target
          # Example key: macos-stable-x86_64-apple-darwin-3k4j234lksjfd9
          key: macos-${{ matrix.channel }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            macos-${{ matrix.channel }}-${{ matrix.target }}-
            macos-${{ matrix.channel }}-
            macos-
      - name: Set Rust Channel
        run: rustup default ${{ matrix.channel }}
      - name: Set Rust Target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --target ${{ matrix.target }}
      - name: Test 
        run: cargo test --target ${{ matrix.target }}

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [ stable, beta ]
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./target
          # Example key: linux-stable-x86_64-unknown-linux-gnu-3k4j234lksjfd9
          key: linux-${{ matrix.channel }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            linux-${{ matrix.channel }}-${{ matrix.target }}-
            linux-${{ matrix.channel }}-
            linux-
      - name: Set Rust Channel
        run: rustup default ${{ matrix.channel }}
      - name: Set Rust Target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --target ${{ matrix.target }}
      - name: Test 
        run: cargo test --target ${{ matrix.target }}
