name: Bump Homebrew

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

env:
  bin: git-view

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          homebrew-tap: sgoudham/homebrew-tap
          create-pullrequest: true
          formula-name: ${{ env.bin }}
          formula-path: Formula/${{ env.bin }}.rb
          tag-name: ${{ github.event.inputs.tag-name }}
          download-url: https://github.com/sgoudham/${{ env.bin }}/releases/download/${{ github.event.inputs.tag-name }}/${{ env.bin }}-x86_64-apple-darwin.tar.gz
          commit-message: |
            {{formulaName}} -> {{version}}
            
            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW }}
